[[ClientHost]]
Pattern = ".+\\.googlebot\\.com"
Description = "Googlebot"

[[ClientHost]]
Pattern = ".+\\.search\\.msn\\.com"
Description = "Bing Bot"

[[ClientHost]]
Pattern = "crawl.+\\.bl\\.semrush\\.com"
Description = "Semrush"

[[ClientHost]]
Pattern = ".+\\.apple\\.com"
Description = "Apple"

[[ClientHost]]
Pattern = ".+\\.aspiegel\\.com"
Description = "Huawei Bot"

[[ClientHost]]
Pattern = ".+\\.ahrefs\\.com"
Description = "ahrefs"